#!/bin/bash


load_conf() {
  local conf
  for conf in "$1"/*.conf; do
    echo "${conf}"
    source "${conf}"
  done
  return 0
}

conf_support() {
  cd `dirname ${BASH_ARGV[0]}`
  echo "`pwd`/$1"
  cd - > /dev/null
}

is_home_dir() {
  cd "$1"
  full_path=`pwd`
  cd - > /dev/null
  [[ "$full_path" = "$HOME" ]]
}

# Get the PATH of this file for relative references
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

export PROFILE_INIT=`readlink ${BASH_ARGV[0]}`
export PROFILE_CORE=`dirname ${PROFILE_INIT}`
export PROFILE_CUSTOM="${PROFILE_CORE}/.."

PLATFORM=`uname`
ORIGINAL_PWD=`pwd`

cd "${HOME}"

load_conf "${SCRIPT_DIR}"
load_conf "${SCRIPT_DIR}/${PLATFORM}"
load_conf "${SCRIPT_DIR}/local"

cd "${ORIGINAL_PWD}"
